# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1c8a1747dc4da299c010232a81289c9637e68b6e968f1896a6234314c9f23a73ce837a41a182b4870eb8f3b22face0d8bd9b1b979f554113ca9d3c9e72e06a62

test:
  secret_key_base: 81ecb4b21492e60ff3f78be6fa16a99e54a4e4b0c0dd92987141110fa589411cbafbf5c4d78f2cb78ca19265a42709d2ce20e15e82f6439617d97ecabf3c8f90

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
